version: '3.8'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: 051203-Fl
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    
    ports:
      - "1433:1433"
    networks:
      - sql_network

networks:
  sql_network:
